.TH tuck 1 "2026-02-13" "tuck" "User Commands"
.SH NAME
tuck \- Modern dotfiles manager with a beautiful CLI
.SH SYNOPSIS
tuck [command] [options]
.SH DESCRIPTION
tuck is a modern dotfiles manager that provides a beautiful CLI
for managing your configuration files across machines.
.SH COMMANDS
.TP
.B init
Initialize tuck
.TP
.B add
Track new dotfiles
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help
.SH FILES
~/.tuck
.SH SEE ALSO
git(1), stow(1)